-- SmilePay Transactions Table
-- Tracks all payment transactions processed through SmilePay gateway

CREATE TABLE IF NOT EXISTS smilepay_transactions (
    id SERIAL PRIMARY KEY,

    -- Reference to payment type
    payment_type VARCHAR(50) NOT NULL,  -- 'subscription', 'campaign', 'booking', 'wallet', 'cart', 'collaboration'
    payment_id INTEGER,  -- ID from respective payment table (nullable for wallet top-ups)

    -- User information
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    user_type VARCHAR(20),  -- 'brand' or 'creator'

    -- Transaction identifiers
    order_reference VARCHAR(100) UNIQUE NOT NULL,  -- Our unique reference
    smilepay_reference VARCHAR(100),  -- SmilePay's internal reference
    transaction_reference VARCHAR(100),  -- Transaction reference from SmilePay response

    -- Payment details
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD',
    currency_code VARCHAR(10),  -- '840' for USD, '924' for ZWL

    -- Payment method
    payment_method VARCHAR(50),  -- 'ecocash', 'innbucks', 'visa', 'mastercard', 'smilecash', 'omari'
    payment_option VARCHAR(50),  -- Payment option from SmilePay response

    -- Transaction status
    status VARCHAR(50) DEFAULT 'PENDING',  -- 'PENDING', 'PAID', 'FAILED', 'CANCELED'
    response_code VARCHAR(50),  -- Response code from SmilePay
    response_message TEXT,  -- Response message from SmilePay

    -- Item details
    item_name VARCHAR(200),
    item_description TEXT,

    -- Customer details
    customer_email VARCHAR(255),
    customer_phone VARCHAR(50),
    customer_first_name VARCHAR(100),
    customer_last_name VARCHAR(100),
    customer_mobile VARCHAR(50),  -- Mobile number used for payment (Ecocash, etc)

    -- URLs for redirects and callbacks
    return_url TEXT,
    result_url TEXT,
    cancel_url TEXT,
    failure_url TEXT,

    -- Fees (from SmilePay)
    client_fee DECIMAL(10, 2),
    merchant_fee DECIMAL(10, 2),

    -- Payment-specific data
    payment_code VARCHAR(100),  -- For Innbucks payment code
    otp_required BOOLEAN DEFAULT FALSE,  -- For OTP-based payments (SmileCash, Omari)

    -- Additional data storage
    extra_data JSON,  -- Store any additional info (payment details, etc) - 'metadata' is reserved by SQLAlchemy
    webhook_data JSON,  -- Store full webhook payload for debugging
    request_data JSON,  -- Store original payment request

    -- Timestamps
    initiated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP,
    failed_at TIMESTAMP,
    canceled_at TIMESTAMP,
    webhook_received_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_smilepay_order_ref ON smilepay_transactions(order_reference);
CREATE INDEX idx_smilepay_payment_type ON smilepay_transactions(payment_type, payment_id);
CREATE INDEX idx_smilepay_user ON smilepay_transactions(user_id);
CREATE INDEX idx_smilepay_status ON smilepay_transactions(status);
CREATE INDEX idx_smilepay_created ON smilepay_transactions(created_at DESC);
CREATE INDEX idx_smilepay_transaction_ref ON smilepay_transactions(transaction_reference);
CREATE INDEX idx_smilepay_method ON smilepay_transactions(payment_method);

-- Add columns to existing payment tables for SmilePay integration

-- Subscriptions table
ALTER TABLE subscriptions
ADD COLUMN IF NOT EXISTS smilepay_order_reference VARCHAR(100);

-- Bookings table
ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS smilepay_order_reference VARCHAR(100);

-- Campaign payments table (if exists)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'campaign_payments') THEN
        ALTER TABLE campaign_payments
        ADD COLUMN IF NOT EXISTS smilepay_order_reference VARCHAR(100);
    END IF;
END $$;

-- Campaign cart table (if exists)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'campaign_cart') THEN
        ALTER TABLE campaign_cart
        ADD COLUMN IF NOT EXISTS smilepay_order_reference VARCHAR(100);
    END IF;
END $$;

-- Collaborations table (if exists)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'collaborations') THEN
        ALTER TABLE collaborations
        ADD COLUMN IF NOT EXISTS smilepay_order_reference VARCHAR(100);
    END IF;
END $$;

COMMENT ON TABLE smilepay_transactions IS 'Tracks all payment transactions through SmilePay gateway';
COMMENT ON COLUMN smilepay_transactions.payment_type IS 'Type of payment: subscription, campaign, booking, wallet, cart, collaboration';
COMMENT ON COLUMN smilepay_transactions.order_reference IS 'Unique order reference generated by our system';
COMMENT ON COLUMN smilepay_transactions.transaction_reference IS 'Transaction reference returned by SmilePay';
COMMENT ON COLUMN smilepay_transactions.payment_method IS 'Payment method used: ecocash, innbucks, visa, mastercard, smilecash, omari';
COMMENT ON COLUMN smilepay_transactions.status IS 'Payment status: PENDING, PAID, FAILED, CANCELED';
COMMENT ON COLUMN smilepay_transactions.payment_code IS 'Payment code for Innbucks transactions';
COMMENT ON COLUMN smilepay_transactions.otp_required IS 'Whether OTP is required for this payment method';
